name: C/C++ CI

on:
  push:
    paths-ignore:
    - 'README.md'
    - 'LICENSE.md'
    - 'tests/**'
    branches: [ master, master-ci ]
  pull_request:
    paths-ignore:
    - 'README.md'
    - 'LICENSE.md'
    - 'tests/**'
    branches: [ master ]

jobs:
  build:

    runs-on: self-hosted
    defaults:
      run:
        shell: bash
    outputs:
      dyninst_lib_path: ${{ steps.get-paths.outputs.dyninst }}
      romp_lib_path:    ${{ steps.get-paths.outputs.romp}}
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Build make files
      run: |
        source ./env_setup.sh   
        mkdir build
        mkdir install
        cd build 
        cmake -DCMAKE_CXX_FLAGS=-std=c++17 \
              -DCMAKE_CXX_COMPILER=g++ -DCMAKE_C_COMPILER=gcc \
              -DCMAKE_INSTALL_PREFIX=`pwd`/../install ..
    - name: Build and install
      run: | 
        source ../env_setup.sh
        make install
      working-directory: ./build
    - name: Get library paths
      id: get-paths 
      run: |
        DYNINST_LIB_PATH=`spack location --install-dir dyninst/pxqjj4q`/lib/libdyninstAPI_RT.so
        ROMP_LIB_PATH=`pwd`/install/lib/libromp.so
        echo "::set-output name=dyninst::$DYNINST_LIB_PATH"
        echo "::set-output name=romp::$ROMP_LIB_PATH"
  simple-test:
    needs: build   
    runs-on: self-hosted
    defaults:
      run:
        shell: bash
    steps:
    - name: Compile simple test program
      run: |
        source ../env_setup.sh  
        g++ -g -fopenmp -lomp simple-omp.cpp -o simple-omp 
      working-directory: ./tests
    - name: Instrument test program
      run: ../install/bin/InstrumentMain --program=./simple-omp
      working-directory: ./tests 
      env:
        DYNINSTAPI_RT_LIB: ${{needs.build.outputs.dyninst_lib_path}}
        ROMP_PATH: ${{needs.build.outputs.romp_lib_path}}
    - name: Run test program
      run: ./simple-omp.inst &> tmp.log
      working-directory: ./tests
      id: run-simple-test
    - name: Check tmp.log
      run: |
        races=$(grep -ce 'data race found:' tmp.log)
        if (( races != 1)); then echo "::error ::False negative on simple-omp"; else exit 0; fi
      working-directory: ./tests
  benchmark-test:
    needs: [build, simple-test]
    runs-on: self-hosted
    defaults:
      run:
        shell: bash
    steps:
    - name: Run test script
      run: |
        ret=$(./ci-tests.sh)
        echo "return value:" $ret
        if [[ $ret -ne 0 ]];  then echo "::error ::ci test failed"; else exit 0; fi
      working-directory: ./tests/ci
